// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamenGamen.Data;

namespace SamenGamen.Migrations
{
    [DbContext(typeof(SamenGamenContext))]
    [Migration("20220406131833_AddAanmeldingen")]
    partial class AddAanmeldingen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("SamenGamen.Models.Aanmelding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Aanmelddatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeelnemerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamevoorstelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeelnemerId");

                    b.HasIndex("GamevoorstelId");

                    b.ToTable("Aanmelding");
                });

            modelBuilder.Entity("SamenGamen.Models.Deelnemer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deelnemer");
                });

            modelBuilder.Entity("SamenGamen.Models.Gamevoorstel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gamevoorstel");
                });

            modelBuilder.Entity("SamenGamen.Models.Aanmelding", b =>
                {
                    b.HasOne("SamenGamen.Models.Deelnemer", "Deelnemer")
                        .WithMany("Aanmeldingen")
                        .HasForeignKey("DeelnemerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SamenGamen.Models.Gamevoorstel", "Gamevoorstel")
                        .WithMany("Aanmeldingen")
                        .HasForeignKey("GamevoorstelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deelnemer");

                    b.Navigation("Gamevoorstel");
                });

            modelBuilder.Entity("SamenGamen.Models.Deelnemer", b =>
                {
                    b.Navigation("Aanmeldingen");
                });

            modelBuilder.Entity("SamenGamen.Models.Gamevoorstel", b =>
                {
                    b.Navigation("Aanmeldingen");
                });
#pragma warning restore 612, 618
        }
    }
}
